# Generated by Django 5.0.4 on 2024-05-11 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('user_login', models.CharField(max_length=100, verbose_name='Логин')),
                ('user_id', models.CharField(max_length=15, verbose_name='Идентификатор')),
                ('user_menu', models.CharField(default='Главное меню', max_length=50, verbose_name='Меню пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100, verbose_name='Класс (программа)')),
                ('favorites', models.TextField(default='{}', verbose_name='Избранное в JSON')),
                ('addition', models.TextField(default='{}', verbose_name='Дополнительные параметры в JSON')),
                ('bot_user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='tbot.botuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Дополнительный параметр',
                'verbose_name_plural': 'Дополнительные параметры',
            },
        ),
    ]
