# Generated by Django 5.0.4 on 2024-05-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='user_login',
            field=models.CharField(default='noname', max_length=100, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='user_name',
            field=models.CharField(default='noname', max_length=100, verbose_name='Имя'),
        ),
    ]
