# Generated by Django 5.0.4 on 2024-05-11 19:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('external_id', models.CharField(max_length=10, unique=True, verbose_name='id Миноблавтотранс')),
                ('finish', models.BooleanField(default=False, verbose_name='Это конечная остановка')),
                ('con_from', models.ManyToManyField(to='schedule.busstop', verbose_name='На эту остановку с каких конечных')),
                ('con_to', models.ManyToManyField(null=True, to='schedule.busstop', verbose_name='С этой остановки на какие конечные')),
            ],
            options={
                'verbose_name': 'Остановка',
                'verbose_name_plural': 'Остановки',
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Номер')),
                ('active', models.BooleanField(default=True, verbose_name='Автобус ходит')),
                ('station', models.ManyToManyField(related_name='buses', to='schedule.busstop', verbose_name='Конечные остановки автобуса')),
            ],
            options={
                'verbose_name': 'Автобус',
                'verbose_name_plural': 'Автобусы',
            },
        ),
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routers', to='schedule.bus', verbose_name='Автобус')),
                ('end', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routers_end', to='schedule.busstop', verbose_name='Конец маршрута')),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routers_start', to='schedule.busstop', verbose_name='Начало маршрута')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(verbose_name='Номер по-порядку')),
                ('bus_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.busstop', verbose_name='Остановка')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_for_router', to='schedule.router', verbose_name='Маршрут')),
            ],
            options={
                'verbose_name': 'Остановка по порядку',
                'verbose_name_plural': 'Остановки по порядку',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='День недели')),
                ('time', models.TimeField(verbose_name='Время')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_for_bus', to='schedule.bus', verbose_name='Автобус')),
                ('bus_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_for_bus_stop', to='schedule.busstop', verbose_name='Остановка')),
            ],
            options={
                'verbose_name': 'Время',
                'verbose_name_plural': 'Время',
            },
        ),
    ]
