# Generated by Django 5.0.4 on 2024-05-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_holiday_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionsForStopNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('options', models.TextField(default='[]', verbose_name='Вариант названия (список)')),
            ],
            options={
                'verbose_name': 'Вариант названия автобусной остановки',
                'verbose_name_plural': 'Варианты названий автобусных остановок',
            },
        ),
    ]
