# Generated by Django 5.0.4 on 2025-07-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_optionsforstopnames'),
    ]

    operations = [
        migrations.CreateModel(
            name='StopGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=100, verbose_name='Остановки')),
            ],
        ),
    ]
