# Generated by Django 5.0.4 on 2025-09-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_stopgroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stopgroup',
            options={'verbose_name': 'Группа остановок назначения', 'verbose_name_plural': 'Группы остановок назначения'},
        ),
        migrations.AlterField(
            model_name='busstop',
            name='con_to',
            field=models.ManyToManyField(to='schedule.busstop', verbose_name='С этой остановки на какие конечные'),
        ),
        migrations.AlterField(
            model_name='stopgroup',
            name='list_name',
            field=models.CharField(max_length=300, verbose_name='Остановки'),
        ),
    ]
