# Generated by Django 5.0.4 on 2024-05-16 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tbot', '0005_botuser_action_count_botuser_schedule_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlisaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(max_length=100, verbose_name='Идентификатор приложения с Алисой')),
                ('parameters', models.TextField(default='{}', verbose_name='Память приложения в JSON')),
                ('passphrase', models.TextField(default='', verbose_name='Парольная фраза для связи с аккаунтом ТГ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tbot.botuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
