# Generated by Django 5.0.4 on 2024-05-18 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alisa', '0001_initial'),
        ('tbot', '0005_botuser_action_count_botuser_schedule_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alisauser',
            name='passphrase',
        ),
        migrations.AlterField(
            model_name='alisauser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tbot.botuser', verbose_name='Пользователь'),
        ),
    ]
