# Generated by Django 5.0.4 on 2024-05-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alisa', '0002_remove_alisauser_passphrase_alter_alisauser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='alisauser',
            name='action_count',
            field=models.IntegerField(default=0, verbose_name='Количество всех действий'),
        ),
        migrations.AddField(
            model_name='alisauser',
            name='last_update',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Последнее обновление'),
        ),
        migrations.AddField(
            model_name='alisauser',
            name='schedule_count',
            field=models.IntegerField(default=0, verbose_name='Количество запросов расписаний'),
        ),
    ]
