# Generated by Django 5.0.4 on 2025-09-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alisa', '0003_alisauser_action_count_alisauser_last_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alisauser',
            name='user_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Обращение к пользователю'),
        ),
    ]
